title: 'Sentosa Development Corporation'
url: 'https://www.sentosa.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    who-we-are:
        output: true
        permalink: '/:collection/:path/:title'
    what-we-do:
        output: true
        permalink: '/:collection/:path/:title'
    partner-us:
        output: true
        permalink: '/:collection/:path/:title'
    careers:
        output: true
resources_name: resources
favicon: /images/favicon.ico
google-analytics: null
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
